### ISSUE TITLE
Missing access to add properties on IAsyncCollector<>

### ISSUE THREAD

**Issue by SurushS** [Azure/azure-functions-rabbitmq-extension#150]
Browsing through the code i saw that with Triggers you have access to the IBasicProperties and the Headers that are available in there. However, if  you want an Azure Function where you output again to another queue, there is currently no way to add properties or headers it seems. Is it possible to add an overload on the AddAsync method on the IAsyncCollector<> ?

**Comment by yojagad** [comment]
This will be supported when this is unblocked (#51) . In other words, this and the other issue pointed out will be revisited when the underlying SDK supports publishing BasicDeliverEventArgs directly rather than individual properties on them. Closing this issue, please keep an eye on that one for updates.
