### ISSUE TITLE
When will you fully support dotnet 3.1?

### ISSUE THREAD

**Issue by kentonbmax** [Azure/azure-functions-rabbitmq-extension#155]
I see your using a version of the RabbitMQ client 5.1.2, that if I'm not mistaken is not compatible with dotnet core 2.2? This is assuming this table is accurate. https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Quick check of the dependencies for this nuget version indicates net standard 1.5.

**Comment by JatinSanghvi** [comment]
Hi @kentonbmax , can you clarify further on this issue? Are you asking to reference a higher version of RabbitMQ client in the project?

According to https://www.nuget.org/packages/RabbitMQ.Client/5.1.2, the client package contains libraries for three .NET versions, including .NET Standard 1.5 and 2.0. The main project in this repo gets built with .NET Standard 2.0 version of RabbitMQ client since it itself targets .NET Standard 2.0. A library targeting lower .NET version should not be a problem. For instance, as per [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support), all clients targeting .NET Core 2.0 and above (including 3.1) should be able to use the RabbitMQ extension library.

Of course, there will be bug fixes and new features included in newer versions of RabbitMQ.Client. For this reason, I will be working on upgrading the client version.

**Comment by JatinSanghvi** [comment]
RabbitMQ client version was upgrade to 6.2.2 in #174. The extension (before and now) should be able to support most version of .NET applications including 3.1 and 6.0.
