### ISSUE TITLE
Question: DLX not working for exchange-routed messages?

### ISSUE THREAD

**Issue by basilfx** [Azure/azure-functions-rabbitmq-extension#165]
I have set-up DLX according to https://www.rabbitmq.com/dlx.html.

My functions listen to a queue. Messages are routed from an exchange to a (direct) queue, using a binding without a routing key.  I noticed that messages routed via exchanges are not republished, and therefore not republished and thus not dead-lettered. Messages published directly to a queue work just fine, but that does not work for a topic-based approach.

I observed the following:

1) Message routed via an exchange to a queue:

```
message.ConsumerTag = "amq.ctag-9eBj3amObQ2Zkvxg23sKZw"
message.Exchange = "NotificationExchange"
message.RoutingKey = ""
```

2) Message directly published to a queue:

```
message.ConsumerTag = "amq.ctag-g3R6R8l-5s8Rh_5PsKj44A"
message.Exchange = ""
message.RoutingKey = "Consumer-NotificationExchange"
```

[This](https://github.com/Azure/azure-functions-rabbitmq-extension/blob/dev/src/Trigger/RabbitMQListener.cs#L171) piece of code is responsible for republishing messages. If I understand it correctly, messages in the first case have an empty routing key, so the messages are republished with `Exchange = string.Emtpy` and `RoutingKey = message.RoutingKey (= string.Empty)`. That explains why it doesn't work.

So my question is: how can I use exchange-based routing in combination with dead-lettering/republishing?

Using extension version 1.0.0 in combination with .NET Core 3.1.

**Comment by stewarthou-jb** [comment]
Yes, we are facing the same issue, because in that line, the publish exchange is set to `""`, which means default exchange, and the `RoutingKey` will be used as destination queue name.
In you case, it's an empty string, probably goes to a blackhole.

If you do want the message be sent back to the same queue, you could just manually set the `RoutingKey` of `BasicDeliverEventArgs` to be the same as the consuming queue name.

**Comment by yvanoers** [comment]
This has been fixed in v2.
