### ISSUE TITLE
ERROR: messages corrupted after republished

### ISSUE THREAD

**Issue by aaguilartablada** [Azure/azure-functions-rabbitmq-extension#207]
Hello.

We are experiencing a strange behaviour with the version 2.0.0. To reproduce this behaviour, I have developed a dummy function that the only thing it does is printing the message and throwing an exception:

```
    [FunctionName("rabbitmq-fail")]
    public async Task RunFail(
      [RabbitMQTrigger(
        "example-queue-fail",
        ConnectionStringSetting = "RabbitMq:ConnectionString")] string message, ILogger logger)
    {
      Console.WriteLine($"RABBITMQ FAIL. Received message: {message}");
      throw new InvalidOperationException("Forced error");
    }
```

If I produce the next message in the queue 'example-queue-fail':
```
{"a":"a","a":"a","a":"a"}
```
everything goes fine (one plus five retries):
```
RABBITMQ FAIL. Received message: {"a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: {"a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: {"a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: {"a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: {"a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: {"a":"a","a":"a","a":"a"}
```

The strange thing occurs when the message is longer. If the message is this:
```
{"a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a"}
```
The first message that my function receives is OK, but the message received for retries is CORRUPTED. The message received by my function for retries include the routing key and the requeueCount header:
```
RABBITMQ FAIL. Received message: {"a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: (example-queue-fail�$<)
requeueCountI�","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: (example-queue-fail�$<)
requeueCountI�","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: (example-queue-fail�$<)
requeueCountI�","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: (example-queue-fail�$<)
requeueCountI�","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a"}
RABBITMQ FAIL. Received message: (example-queue-fail�$<)
requeueCountI�","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a","a":"a"}
```

**Comment by JatinSanghvi** [comment]
- I am able to reproduce the error. It is intermittent. Sometimes, it happens on the first republish, sometimes after a few republishes.

- The bug seems be inside either RabbitMQ client or the service. I logged the input message inside the extension code as soon as it is received and the output message just before it gets republished. The output message is the exact string in both working on corrupted case but intermittently, the input message in subsequent retry is logged as corrupted.

- The length of string is significant. I couldn't reproduce the error with message body of size 512 characters even after trying many times, but the issue gets reproduced most of the times if body length is 513 characters. It is not required for the message body to be a JSON string.

- The extra string is the queue name and message header. Header `requestCount` is added by the RabbitMQ extension to the message to keep track of number of retries.

- Also, I tried adding 5 second delay between the republishes, the issue still persisted.

I will check on RabbitMQ forums if the issue is known. Note that we upgraded RabbitMQ client in v2.0.0 extension version, so it is possible there is a regression introduced in the latest client version.

**Comment by JatinSanghvi** [comment]
Unable to find any related issue on https://github.com/rabbitmq/rabbitmq-dotnet-client/issues but also unable to reproduce the error after upgrading to RabbitMQ client 6.4.0. I tried message body of size 8192 characters but did not find the republished messages to ever be corrupted.

I will create a pull request soon. Since this is a major issue, I will also create a new extension release (possibly 2.0.1) after due testing. Thanks for creating the issue.

**Comment by aaguilartablada** [comment]
Thank you so much @JatinSanghvi . When do you estimate that release 2.0.1 will be available?

**Comment by JatinSanghvi** [comment]
I will try to get the new version out by end of Tuesday. Need to complete one round of testing before creating a release.

**Comment by JatinSanghvi** [comment]
Version 2.0.1. is released now. https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.RabbitMQ/2.0.1

**Comment by aaguilartablada** [comment]
Hello again @JatinSanghvi . I have seen the version 2.0.1 published in nuget.org (https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.RabbitMQ). So, I have tested it.

BAD NEWS: the problem is still there. When the message is long my function receives the message corrupted for retries.
