### ISSUE TITLE
Binding to non-json payload does not work with non-dotnet languages

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-rabbitmq-extension#80]
When I try to run the app in Python it throws the following after triggering:

> [11/20/19 7:07:17 PM] Executed 'Functions.RabbitMqTrigger' (Failed, Id=cf468829-43b7-4ec3-9baf-ab44b3e27e17)
[11/20/19 7:07:17 PM] System.Private.CoreLib: Exception while executing function: Functions.RabbitMqTrigger. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'msg'. Newtonsoft.Json: Unexpected character encountered while parsing value: h. Path '', line 0, position 0.

I have a repro of my app here: https://github.com/jeffhollan/repro-python-rabbitmq

Related to #47

**Comment by ankitkumarr** [comment]
I ran into this with Node as well. It will only work if the payload in the message is a valid JSON.

**Here's why I think this happens:**

The extension attaches converters from `BasicDeliverEventArgs` to `string` and also from `BasicDeliverEventArgs` to any `POCO` ([here](https://github.com/Azure/azure-functions-rabbitmq-extension/blob/dev/src/Config/RabbitMQExtensionConfigProvider.cs#L63-L67)).

During the binding code path on execution, `TriggerAdapterBindingProvider` is used to pick the right converter for this binding contract. As you can see [from the code here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/TriggerAdapterBindingProvider.cs#L54-L75), the order of priority goes --
`byte[]`, `JObject`, `JArray`, `string`.

Because the RabbitMQ extension adds a POCO converter, the code picks that as the selected converter as it works with `JObject` (higher priority than string). This means that now WebJobs tries to convert the payload to JObject using the POCO converter available. Ideally it should have picked the converter for `string`, as that is the requestedType.

If I remove the POCO converter from the extension, out of proc languages start working as expected.


I think there's two fixes possible --
1. We update Webjobs to take into account the `requestedType` [here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/TriggerAdapterBindingProvider.cs#L54), and if a converter is available for that, pick that. This may  be a breaking change for other extensions.
2. We remove the POCO converter... This doesn't sound like the right fix, but is the easiest resolution.


cc: @pragnagopa, @fabiocav

**Comment by fabiocav** [comment]
@jeffhollan how do you want to prioritize work here?

**Comment by jeffhollan** [comment]
I think this warrants a fix in the next few weeks assuming we aren’t having to cut a critical fix in another area.  FWIW I think the dapr stuff Connor is working on is impacted by the same behavior and not sure if he already worked around it there too

**Comment by pragnagopa** [comment]
@ankitkumarr - thanks for the details. I wonder if there is something we are missing here as other extensions support binding to POCOs as well and work with out-of-proc languages. I will take a look.

**Comment by ankitkumarr** [comment]
@pragnagopa, most of the other extensions do not use these new interfaces, I think they implement `ITriggerBindingStrategy` and those other types that do not end up executing `TriggerAdapterBindingProvider` in the stack.

The one extension that I know uses the new APIs similar to RabbitMQ is EventGrid. EventGrid payloads are always a valid JSON, so it never runs into this. I tried it locally and saw that every time the payload uses the POCO converter to convert to JObject even for out of proc languages. Even if I remove all string converters for EventGrid, it continues to work, as the POCO converter is the one getting used.

**Comment by pragnagopa** [comment]
So we should figure out Option 1 you mentioned above without breaking changes? Otherwise this would continue to be an issue for any "new extension" that will be use 'TriggerAdapterBindingProvider'

**Comment by ankitkumarr** [comment]
Yes, I agree. I think we'd need to make sure we don't accidentally break any extension, as changing that changes how types may be converted. I only know of EventGrid, but when we do the work, we'd have to verify all extensions that maybe using this code-path continue to work as expected.

**Comment by fabiocav** [comment]
@jeffhollan (and @dariagrigoriu), this has been assigned to triaged but not prioritized. We need some guidance on how to prioritize some of these issues here.
