### ISSUE TITLE
Add support for connecting to user defined Virtual Hosts

### ISSUE THREAD

**Issue by markm9199** [Azure/azure-functions-rabbitmq-extension#81]
If I've understood correctly then this will only connect to queues in the Virtual Host called \

I had to give my user account access to \ and move the queue I was testing with into \ otherwise it would not work.

Are there any plans to extend to user defined Virtual Hosts?

Also, any plans to be able to publish to an Exchange with a routing key rather than directly to a queue?

**Comment by RobBowman** [comment]
Any update on this please?

**Comment by ThejaChoudary** [comment]
@markm9199  Apologies for the late reply 
Can you please provide us with more info about this to investigate further and also please refer the [link](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/dedicated-hosts)  for your guidance.


Thank You for your patience .

**Comment by markm9199** [comment]
I don't understand why you have asked me to look at a link to Azure Dedicated Hosts, I think perhaps there is a misunderstanding? 

I am talking about a feature of RabbitMQ called Virtual Hosts. It is normal in a large Rabbit MQ installation, to group exchanges and queues using different Virtual Hosts, on the Rabbit MQ. I assume as a rabbit extension developer you are familiar with this concept?

My issue is that this extension does not allow me to specify which Virtual Host to use, in fact it defaults to the top level Virtual Host , called '\\'. **I would like to be able to specify the Rabbit Virtual Host**. 

My business has many exchanges and queues on a single Rabbit MQ cluster, and they are grouped into Virtual Hosts. I cannot change this and so if I cannot specify the Virtual Host then I cannot connect to the my queues with this extension.

Here is an image snipped from a Rabbit MQ management console, showing a section where one can select and create Virtual Hosts. This is just to indicate to you what I mean by Virtual Hosts.

![image](https://user-images.githubusercontent.com/51416865/88288370-9953ac80-cceb-11ea-853c-846b79386e65.png)

Is this enough information?

**Comment by markm9199** [comment]
@ThejaChoudary any update after my recent comments?

**Comment by ThejaChoudary** [comment]
@pragnagopa --Can you please take a look .Thank you !

**Comment by pragnagopa** [comment]
@markm9199  - Thanks for the feature request.

Moved this to Triaged.

**Comment by Socolin** [comment]
This seems to be already possible to use vhosts using connection string like
```
  "connectionStrings": {
    "rabbitMQ": "amqp://localhost/azure-rabbitmq"
  }
```
But the vhost parameter is missing from `RabbitMQAttribute` when using `HostName` / `UserName` / `Password`

**Comment by cachai2** [comment]
@yojagad to investigate

**Comment by Socolin** [comment]
@cachai2  there is already a pull request here (got closed by the bot...) but I fixed last reviews so it should be ready now. https://github.com/Azure/azure-functions-rabbitmq-extension/pull/95

**Comment by kentonbmax** [comment]
Can someone please confirm this is implemented and working? it seems specifying in the uri does not work. in v1.0.0

**Comment by Socolin** [comment]
> Can someone please confirm this is implemented and working? it seems specifying in the uri does not work. in v1.0.0

This repository seems dead, this feature **is not available** yet, my PR was close by the bot after I fixed requested change and nobody have looked for it since january.

@jeffhollan Could you give us an ETA when this feature will be finally available. More generally when will we be able to use this extension without having to apply custom patch ? It' s documented as an available feature https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-rabbitmq but clearly it's not production ready.

**Comment by JatinSanghvi** [comment]
As mentioned in https://github.com/Azure/azure-functions-rabbitmq-extension/issues/81#issuecomment-708888734, connection strings support virtual hosts already. RabbitMQ v2.x will remove support for individual connection elements. Currently we have `enableSsl`, `host`, `port`, `username` and `password` properties. Since the issue only existed when user passes individual connection fields instead of the whole connection URI, the lack of support for `vhost` binding field won't be in question.
