### ISSUE TITLE
Method not found: 'Byte[] RabbitMQ.Client.Events.BasicDeliverEventArgs.get_Body()'.

### ISSUE THREAD

**Issue by ianvink** [Azure/azure-functions-rabbitmq-extension#89]
Hi,

I have hosted RabbitMQ in a Docker container and via a simple Asp.Net Core web site confirmed that I can send messages. The management console confirms.

I have created a simple Azure Function, run locally, but when it connects, it gets the error when the function runs in debug on my dev box:
     
    Method not found: 'Byte[] RabbitMQ.Client.Events.BasicDeliverEventArgs.get_Body()'.

I do get a consumer listed once the Function runs, but the Function crashes after it gets the above error.

![image](https://user-images.githubusercontent.com/112916/82964504-7bcbc600-9f7a-11ea-88aa-6a2f4507c58f.png)

My function, run locally in Visual Studio 2019, is very simple:

     public static class TriggerFunction
     {
        [FunctionName("TriggerFunction")]
        public static void Run(
            [RabbitMQTrigger("hello")] string message, ILogger log)
        {
            log.LogInformation($"************* Message received from RabbitMQ trigger: {message}");
        }
     }

My NuGets are:

     <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.RabbitMQ" Version="0.2.2029-beta" />
     <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
     <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
     <PackageReference Include="RabbitMQ.Client" Version="6.0.0" />

**Comment by ianvink** [comment]
I found the issue. This project doesn't support **RabbitMQ.Client version 6**.

**FAILS:**

       <PackageReference Include="RabbitMQ.Client" Version="6.0.0" />

**WORKS:**

       <PackageReference Include="RabbitMQ.Client" Version="5.2.0" />

Thanks for a great tools guys

**Comment by Cogax** [comment]
I have the same problem. For me, this is still a bug, as we can define the version more specific, as stated here https://docs.microsoft.com/en-us/nuget/concepts/package-versioning.

**Comment by JatinSanghvi** [comment]
@Cogax, I do not think that additional reference to `RabbitMQ.Client` package would be required in the Azure Functions project. The RabbitMQ client assembly should get added to the project-output folder automatically with the extension, since it's set as [dependency in the NuGet package](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.RabbitMQ/1.1.0#dependencies-tab). For example, check [this file](https://github.com/JatinSanghvi/function-app-rabbitmq/blob/main/RabbitMqExample.csproj). Let me know if you get any error building your project with the reference to RabbitMQ client removed.

I will need to close #176 as we have upgraded RabbitMQ client version in the extension repo. We should get a pre-release version of extension out in a week or two.
